<script setup>
import { ref, onMounted } from 'vue'
const emit = defineEmits(['login-sucesso','ir-para-cadastro'])
const authForm = ref({ usuario:'', senha:'' }); const erroAuth = ref(''); const carregando = ref(false)
const lidarLogin = async () => { erroAuth.value=''; if(!authForm.value.usuario||!authForm.value.senha){erroAuth.value='Preencha o usuário e a senha.';return}; carregando.value=true; try{const res=await fetch('https://meusocial.onrender.com/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(authForm.value)});const data=await res.json();if(data.sucesso)emit('login-sucesso',data.usuario,data.foto_perfil||'');else erroAuth.value=data.erro||'Usuário ou senha incorretos.'}catch(e){erroAuth.value='Erro de conexão com o servidor.'}finally{carregando.value=false}}
const handleGoogleResponse=async(response)=>{try{const res=await fetch('https://meusocial.onrender.com/api/auth/google',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:response.credential})});const data=await res.json();if(data.sucesso){localStorage.setItem('foto_perfil',data.foto_perfil||'');emit('login-sucesso',data.usuario,data.foto_perfil||'')}else erroAuth.value=data.erro||'Erro ao autenticar com o Google.'}catch(e){erroAuth.value='Erro de conexão ao validar login com Google.'}}
const inicializarGoogle=()=>{if(window.google){window.google.accounts.id.initialize({client_id:'135718805364-1jlfpba4t7u1680lad1sgu2qe446c67h.apps.googleusercontent.com',callback:handleGoogleResponse});const el=document.getElementById('google-btn');if(el)window.google.accounts.id.renderButton(el,{theme:'outline',size:'large',width:'100%',text:'continue_with'})}}
onMounted(()=>{if(!document.getElementById('google-script')){const s=document.createElement('script');s.id='google-script';s.src='https://accounts.google.com/gsi/client';s.async=true;s.defer=true;s.onload=inicializarGoogle;document.head.appendChild(s)}else setTimeout(inicializarGoogle,200)})
</script>
<template><div class="min-h-screen bg-gradient-to-br from-[#554CE8] via-[#756CF5] to-[#FF6B9D] flex items-center justify-center p-4 relative overflow-hidden"><div class="absolute inset-0 pointer-events-none"><div class="absolute -top-32 -left-32 w-80 h-80 bg-white/10 rounded-full blur-3xl"></div><div class="absolute -bottom-40 -right-20 w-96 h-96 bg-white/10 rounded-full blur-3xl"></div><div class="absolute top-20 right-16 text-4xl opacity-30 rotate-12">♥</div><div class="absolute bottom-24 left-12 text-3xl opacity-30 -rotate-12">✦</div></div><div class="relative w-full max-w-md bg-white/95 backdrop-blur rounded-[2rem] p-7 sm:p-9 shadow-2xl z-10"><div class="text-center mb-7"><div class="inline-flex items-center justify-center w-16 h-16 bg-gradient-to-tr from-[#6C63FF] to-[#FF6B9D] rounded-2xl shadow-lg text-white text-3xl mb-4 animate-pulse">♥</div><h2 class="text-3xl font-black text-[#211F3B] tracking-tight">Desabafa Coração</h2><p class="text-sm text-[#77748B] mt-2 leading-relaxed">Um espaço seguro para falar, ouvir e receber apoio.</p></div><form @submit.prevent="lidarLogin" class="space-y-4"><div><label class="form-label">Usuário ou e-mail</label><input v-model="authForm.usuario" type="text" placeholder="Digite seu usuário" autocomplete="username" class="form-input" /></div><div><label class="form-label">Senha</label><input v-model="authForm.senha" type="password" placeholder="••••••••" autocomplete="current-password" class="form-input" /></div><div v-if="erroAuth" class="bg-red-50 border border-red-200 text-red-600 text-xs p-3.5 rounded-xl text-center font-semibold">{{ erroAuth }}</div><button type="submit" :disabled="carregando" class="w-full bg-gradient-to-r from-[#6C63FF] to-[#FF6B9D] hover:scale-[1.01] active:scale-95 text-white font-bold py-3.5 rounded-xl shadow-lg shadow-[#6C63FF]/30 transition-all flex justify-center gap-2"><span v-if="carregando" class="animate-spin">◌</span>{{ carregando?'Entrando...':'Entrar e desabafar' }}</button></form><div class="mt-6"><div class="relative flex items-center"><div class="flex-grow border-t border-[#e9ecef]"></div><span class="mx-4 text-xs text-[#adb5bd] uppercase tracking-widest font-bold">ou</span><div class="flex-grow border-t border-[#e9ecef]"></div></div><div id="google-btn" class="flex justify-center mt-4 overflow-hidden rounded-xl"></div></div><div class="mt-6 text-center"><button @click="emit('ir-para-cadastro')" class="text-sm text-[#77748B] hover:text-[#6C63FF] font-medium">Ainda não participa? <span class="text-[#6C63FF] underline font-bold">Crie sua conta</span></button></div><p class="text-center text-[11px] text-[#aaa6bd] mt-5">🔒 Seus sentimentos merecem privacidade.</p></div></div></template>
<style>.form-label{display:block;font-size:.68rem;font-weight:800;color:#77748b;text-transform:uppercase;letter-spacing:.08em;margin-bottom:6px}.form-input{width:100%;background:#f8f7ff;border:1px solid #e8e5f3;border-radius:13px;padding:13px 15px;font-size:.88rem;color:#211f3b;outline:0;transition:.2s}.form-input:focus{border-color:#6c63ff;box-shadow:0 0 0 4px #6c63ff1c}</style>
